package com.github.bh.hjob.core.persist.base.model;

import java.util.Date;

public class ScheduleJob {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.job_id
     *
     * @mbggenerated
     */
    private Long jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.job_name
     *
     * @mbggenerated
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.job_group
     *
     * @mbggenerated
     */
    private String jobGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.job_notify_key
     *
     * @mbggenerated
     */
    private String jobNotifyKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.job_status
     *
     * @mbggenerated
     */
    private Integer jobStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.job_detail_status
     *
     * @mbggenerated
     */
    private String jobDetailStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.cronexpression
     *
     * @mbggenerated
     */
    private String cronexpression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.previous_time
     *
     * @mbggenerated
     */
    private Date previousTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.next_time
     *
     * @mbggenerated
     */
    private Date nextTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.job_id
     *
     * @return the value of schedule_job.job_id
     *
     * @mbggenerated
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.job_id
     *
     * @param jobId the value for schedule_job.job_id
     *
     * @mbggenerated
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.job_name
     *
     * @return the value of schedule_job.job_name
     *
     * @mbggenerated
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.job_name
     *
     * @param jobName the value for schedule_job.job_name
     *
     * @mbggenerated
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.job_group
     *
     * @return the value of schedule_job.job_group
     *
     * @mbggenerated
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.job_group
     *
     * @param jobGroup the value for schedule_job.job_group
     *
     * @mbggenerated
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup == null ? null : jobGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.job_notify_key
     *
     * @return the value of schedule_job.job_notify_key
     *
     * @mbggenerated
     */
    public String getJobNotifyKey() {
        return jobNotifyKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.job_notify_key
     *
     * @param jobNotifyKey the value for schedule_job.job_notify_key
     *
     * @mbggenerated
     */
    public void setJobNotifyKey(String jobNotifyKey) {
        this.jobNotifyKey = jobNotifyKey == null ? null : jobNotifyKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.job_status
     *
     * @return the value of schedule_job.job_status
     *
     * @mbggenerated
     */
    public Integer getJobStatus() {
        return jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.job_status
     *
     * @param jobStatus the value for schedule_job.job_status
     *
     * @mbggenerated
     */
    public void setJobStatus(Integer jobStatus) {
        this.jobStatus = jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.job_detail_status
     *
     * @return the value of schedule_job.job_detail_status
     *
     * @mbggenerated
     */
    public String getJobDetailStatus() {
        return jobDetailStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.job_detail_status
     *
     * @param jobDetailStatus the value for schedule_job.job_detail_status
     *
     * @mbggenerated
     */
    public void setJobDetailStatus(String jobDetailStatus) {
        this.jobDetailStatus = jobDetailStatus == null ? null : jobDetailStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.cronexpression
     *
     * @return the value of schedule_job.cronexpression
     *
     * @mbggenerated
     */
    public String getCronexpression() {
        return cronexpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.cronexpression
     *
     * @param cronexpression the value for schedule_job.cronexpression
     *
     * @mbggenerated
     */
    public void setCronexpression(String cronexpression) {
        this.cronexpression = cronexpression == null ? null : cronexpression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.previous_time
     *
     * @return the value of schedule_job.previous_time
     *
     * @mbggenerated
     */
    public Date getPreviousTime() {
        return previousTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.previous_time
     *
     * @param previousTime the value for schedule_job.previous_time
     *
     * @mbggenerated
     */
    public void setPreviousTime(Date previousTime) {
        this.previousTime = previousTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.next_time
     *
     * @return the value of schedule_job.next_time
     *
     * @mbggenerated
     */
    public Date getNextTime() {
        return nextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.next_time
     *
     * @param nextTime the value for schedule_job.next_time
     *
     * @mbggenerated
     */
    public void setNextTime(Date nextTime) {
        this.nextTime = nextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.description
     *
     * @return the value of schedule_job.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.description
     *
     * @param description the value for schedule_job.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ScheduleJob other = (ScheduleJob) that;
        return (this.getJobId() == null ? other.getJobId() == null : this.getJobId().equals(other.getJobId()))
            && (this.getJobName() == null ? other.getJobName() == null : this.getJobName().equals(other.getJobName()))
            && (this.getJobGroup() == null ? other.getJobGroup() == null : this.getJobGroup().equals(other.getJobGroup()))
            && (this.getJobNotifyKey() == null ? other.getJobNotifyKey() == null : this.getJobNotifyKey().equals(other.getJobNotifyKey()))
            && (this.getJobStatus() == null ? other.getJobStatus() == null : this.getJobStatus().equals(other.getJobStatus()))
            && (this.getJobDetailStatus() == null ? other.getJobDetailStatus() == null : this.getJobDetailStatus().equals(other.getJobDetailStatus()))
            && (this.getCronexpression() == null ? other.getCronexpression() == null : this.getCronexpression().equals(other.getCronexpression()))
            && (this.getPreviousTime() == null ? other.getPreviousTime() == null : this.getPreviousTime().equals(other.getPreviousTime()))
            && (this.getNextTime() == null ? other.getNextTime() == null : this.getNextTime().equals(other.getNextTime()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getJobId() == null) ? 0 : getJobId().hashCode());
        result = prime * result + ((getJobName() == null) ? 0 : getJobName().hashCode());
        result = prime * result + ((getJobGroup() == null) ? 0 : getJobGroup().hashCode());
        result = prime * result + ((getJobNotifyKey() == null) ? 0 : getJobNotifyKey().hashCode());
        result = prime * result + ((getJobStatus() == null) ? 0 : getJobStatus().hashCode());
        result = prime * result + ((getJobDetailStatus() == null) ? 0 : getJobDetailStatus().hashCode());
        result = prime * result + ((getCronexpression() == null) ? 0 : getCronexpression().hashCode());
        result = prime * result + ((getPreviousTime() == null) ? 0 : getPreviousTime().hashCode());
        result = prime * result + ((getNextTime() == null) ? 0 : getNextTime().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jobId=").append(jobId);
        sb.append(", jobName=").append(jobName);
        sb.append(", jobGroup=").append(jobGroup);
        sb.append(", jobNotifyKey=").append(jobNotifyKey);
        sb.append(", jobStatus=").append(jobStatus);
        sb.append(", jobDetailStatus=").append(jobDetailStatus);
        sb.append(", cronexpression=").append(cronexpression);
        sb.append(", previousTime=").append(previousTime);
        sb.append(", nextTime=").append(nextTime);
        sb.append(", description=").append(description);
        sb.append("]");
        return sb.toString();
    }
}