/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.github.bh.hjob.core.model;
/**
 * @author xiaobenhai
 */
public class ScheduleJobDeleteRequest {
  /**
   * 任务Id
   *
   */
  public String jobName; // required
  /**
   * 调度任务组
   *
   */
  public String jobGroup; // optional

  public String getJobGroup() {
    return jobGroup;
  }

  public void setJobGroup(String jobGroup) {
    this.jobGroup = jobGroup;
  }

  public String getJobName() {
    return jobName;
  }

  public void setJobName(String jobName) {
    this.jobName = jobName;
  }
}