/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.github.bh.hjob.core.model;

import java.util.List;
/**
 * @author xiaobenhai
 */
public class ScheduleJobQueryResponse {
  public List<ScheduleJobWrapper> joblist; // required

  public List<ScheduleJobWrapper> getJoblist() {
    return joblist;
  }

  public void setJoblist(List<ScheduleJobWrapper> joblist) {
    this.joblist = joblist;
  }
}