/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.github.bh.hjob.core.model;
/**
 * @author xiaobenhai
 */
public class ScheduleJobWrapper {
  public long jobId; // required
  public String jobName; // required
  public String jobGroup; // optional
  public String jobDetailStatus; // optional
  public int jobStatus; // optional
  public String cronexpression; // optional
  public long nextTime; // optional
  public long previousTime; // optional
  public String description; // optional
  public String mqKey; // optional


  public long getJobId() {
    return jobId;
  }

  public void setJobId(long jobId) {
    this.jobId = jobId;
  }

  public String getJobName() {
    return jobName;
  }

  public void setJobName(String jobName) {
    this.jobName = jobName;
  }

  public String getJobGroup() {
    return jobGroup;
  }

  public void setJobGroup(String jobGroup) {
    this.jobGroup = jobGroup;
  }

  public String getJobDetailStatus() {
    return jobDetailStatus;
  }

  public void setJobDetailStatus(String jobDetailStatus) {
    this.jobDetailStatus = jobDetailStatus;
  }

  public int getJobStatus() {
    return jobStatus;
  }

  public void setJobStatus(int jobStatus) {
    this.jobStatus = jobStatus;
  }

  public String getCronexpression() {
    return cronexpression;
  }

  public void setCronexpression(String cronexpression) {
    this.cronexpression = cronexpression;
  }

  public long getNextTime() {
    return nextTime;
  }

  public void setNextTime(long nextTime) {
    this.nextTime = nextTime;
  }

  public long getPreviousTime() {
    return previousTime;
  }

  public void setPreviousTime(long previousTime) {
    this.previousTime = previousTime;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getMqKey() {
    return mqKey;
  }

  public void setMqKey(String mqKey) {
    this.mqKey = mqKey;
  }
}