/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.github.bh.hjob.core.model;
/**
 * @author xiaobenhai
 */
public class ScheduleJobOperRequest {
  /**
   * 任务名称
   *
   */
  public String jobName; // required
  /**
   * 任务组
   *
   */
  public String jobGroup; // required
  /**
   * 任务操作
   *
   */
  public int oper; // required

  public String getJobName() {
    return jobName;
  }

  public void setJobName(String jobName) {
    this.jobName = jobName;
  }

  public String getJobGroup() {
    return jobGroup;
  }

  public void setJobGroup(String jobGroup) {
    this.jobGroup = jobGroup;
  }

  public int getOper() {
    return oper;
  }

  public void setOper(int oper) {
    this.oper = oper;
  }
}